apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts
          ports:
            - containerPort: 9000
          env:
            - name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://postgresql:5432/sonarqube"
            - name: SONARQUBE_JDBC_USERNAME
              value: "sonar"
            - name: SONARQUBE_JDBC_PASSWORD
              value: "sonar"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          volumeMounts:
            - name: sonarqube-data
              mountPath: "/opt/sonarqube/data"
            - name: sonarqube-logs
              mountPath: "/opt/sonarqube/logs"
            - name: sonarqube-extensions
              mountPath: "/opt/sonarqube/extensions"
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-pvc
        - name: sonarqube-logs
          persistentVolumeClaim:
            claimName: sonarqube-logs-pvc
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions-pvc
