apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sonarqube-sc
provisioner: kubernetes.io/no-provisioner  # No dynamic provisioning
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarqube-sc  # Added storageClassName
  hostPath:
    path: "/mnt/data/sonarqube"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
spec:
  volumeName: sonarqube-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sonarqube-sc  # Added storageClassName to match PV
