apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarqube-sc
  hostPath:
    path: "/mnt/data/sonarqube/extensions"
    type: DirectoryOrCreate
  claimRef:
    name: sonarqube-extensions-pvc
    namespace: sonarqube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sonarqube-sc
