apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions-pv
  namespace: sonarqube
spec:
  capacity:
    storage: 5Gi  # Adjust size if needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarqube-sc
  hostPath:
    path: "/mnt/data/sonarqube/extensions"  # Change this path as needed
